### ISSUE TITLE
By aligning items to center carousel crops images

### ISSUE THREAD

**Issue by Thunderer0** [Learus/react-material-ui-carousel#139]
in version 2.3.1
![previous version](https://user-images.githubusercontent.com/76218241/147045378-acb1caed-5faa-423f-a74c-7096fc85a706.png)

in current version
![latest version](https://user-images.githubusercontent.com/76218241/147045476-8e170c7d-1a2a-40d7-a3da-adf01d20139b.png)

These are results with same piece of code but different versions

**Comment by Learus** [comment]
Hello. Would you be able to share the code that has this problem? A CodeSandbox would be appreciated.

**Comment by Thunderer0** [comment]
`         <div className="ProductDetails">
            <div>
              <Carousel>
                {product.images &&
                  product.images.map((item, i) => (
                    <img
                      className="CarouselImage"
                      key={i}
                      src={item.url}
                      alt={`${i} Slide`}
                    />
                  ))}
              </Carousel>
            </div>
          </div>` 
This was the react code 
.ProductDetails>div {
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    **align-items: center;**
    padding: 2vmax;
    box-sizing: border-box;
    border: 1px solid white;
}
and this was it's css 
by simply changing version of Carousel my output was changed so I don't think so there would be any problem with code

**Comment by Learus** [comment]
Any specific frameworks used, other than `react`? I'm referring to stuff like `Nextjs`, `Gatsby` or something similar.

**Comment by Thunderer0** [comment]
No I've only used react

**Comment by Learus** [comment]
[This is the sandbox I used to test](https://codesandbox.io/s/distracted-dhawan-9vsc4?file=/src/App.js:181-184)

This is the css you should be using here:
```css
.ProductDetails {
  display: flex;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
  padding: 2vmax;
  border: 1px solid white;
}

.ProductDetails > div {
  width: 100%;
}
```
